feat: add support for overriding subgraph routing urls
wundergraph/cosmo pull request #109
Opened 2023-09-24 11:26 UTC by cs-clarence

## Motivation and Context
Allows overriding routing urls for subgraphs via `config.yaml`:
```yaml
override_routing_url:
  subgraphs:
    some-subgraph: http//new-subgraph-routing-url.com/graphql
```

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2023-09-24 19:31 UTC, StarpTech commented
Hi @ cs-clarence, can you give more context on why this feature is valuable to add to the core?

The routing URL is stored in the route config which is fetched from the controlplane. The integrity of the URL is important to enrich requests with proper trace attributes. If we allow arbitrary subgraph URLs we lose the connection.
In order to change the subgraph URL you have to update the subgraph with the wgc cli.

2023-09-24 22:59 UTC, cs-clarence commented
Hey @StarpTech, I've seen this feature in the apollo router [here](https://www.apollographql.com/docs/router/configuration/overview#subgraph-routing-urls). 

It would be useful for routers inside a k8s cluster so they can use the cluster-local DNS name while keeping the public DNS name config in the control plane. I understand that this is a niche use case, so feel free to close this if you deem this a not-useful feature.

2023-09-25 09:06 UTC, StarpTech commented
> It would be useful for routers inside a k8s cluster so they can use the cluster-local DNS name while keeping the public DNS name config in the control plane. I understand that this is a niche use case, so feel free to close this if you deem this a not-useful feature.

This is a good use case! I'll come back later.

2023-09-28 22:45 UTC, jgautheron commented
Got a similar use case here, currently replacing it before deployment with `sed` but would be cleaner to allow an override either by config and/or env var.

2023-09-29 10:49 UTC, StarpTech commented
@jgautheron thanks for the feedback. Will look into it.

2023-09-29 23:02 UTC, StarpTech requested changes

2023-09-29 23:16 UTC, cs-clarence commented on router/internal/config/config.go
> +	MaxAttempts int           `yaml:"max_attempts" default:"5"                                        validate:"required,min=1,required_if=Algorithm backoff_jitter"`
Oh I didn't realize I had it on. Will revert it

2023-09-30 10:52 UTC, StarpTech requested changes

2023-09-30 10:52 UTC, StarpTech commented on router/core/router.go
> +	for _, sg := range cfg.Subgraphs {
Put this logic in a method for better readability e.g. `configureSubgraphOverwrites`.

2023-09-30 10:55 UTC, StarpTech requested changes

2023-09-30 10:55 UTC, StarpTech commented on router/core/router.go
> +			rawURL := s.RoutingUrl
Move the validation logic into the proposed `configureSubgraphOverwrites` and return the error when a subgraph has an invalid url. Although the URLs are already validated through the validate config package. I'm also fine with both.

2023-09-30 22:12 UTC, StarpTech requested changes

2023-09-30 22:12 UTC, StarpTech commented on router/core/router.go
> +	httpRouter.Use(func(h http.Handler) http.Handler {
Mistake? This is an empty middleware.

2023-09-30 22:12 UTC, StarpTech commented on router/core/router.go
> +	// Validate all the URLs first before we start overriding
Much better :+1:

2023-09-30 22:16 UTC, cs-clarence commented on router/core/router.go
> +	httpRouter.Use(func(h http.Handler) http.Handler {
Oh yeah, I forgot to remove it

2023-10-04 18:30 UTC, StarpTech commented
@cs-clarence ready for review again?

2023-10-04 22:39 UTC, cs-clarence commented
@StarpTech yes

2023-10-05 12:24 UTC, StarpTech commented
I continue your work here #152 I found a couple of issues and fixed them there. I hope it's okay. I could not push the branch here.

2023-10-05 12:24 UTC, closed without merging

2023-10-05 20:26 UTC, cs-clarence commented
@StarpTech yeah that's alright, it's better for you to take over because although I tested the code, I haven't verified that it works without issues.

2023-10-05 21:03 UTC, StarpTech commented
@cs-clarence thank you again for pushing this initiative.