fix: schema search ui
wundergraph/cosmo pull request #1096
Opened 2024-08-19 17:07 UTC by thisisnithin

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-08-19 17:20 UTC, StarpTech requested changes

2024-08-19 17:20 UTC, StarpTech commented on studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/index.tsx
> +                {router.query.fieldName}fiuwevbifuwebfiuwbfiweufvbweuifvb
😄 gotcha!

2024-08-20 04:00 UTC, thisisnithin commented on studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/index.tsx
> +                {router.query.fieldName}fiuwevbifuwebfiuwbfiweufvbweuifvb
Lol, removed

2024-08-20 08:16 UTC, StarpTech approved these changes
LGTM

2024-08-20 08:24 UTC, merged