chore: setup connect-go proto files
wundergraph/cosmo pull request #1169
Opened 2024-09-13 14:49 UTC by AndreasZeissner

## Motivation and Context

This is used for https://github.com/wundergraph/terraform-provider-cosmo.

The package can be used like this: 

```
go get github.com/wundergraph/cosmo@638540986b469dxxxxxxxxxxxxxxxxxx
```

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-09-13 14:56 UTC, StarpTech requested changes
How do we detected outdated artifacts? Is it running when the controlplane changes?

2024-09-13 17:15 UTC, AndreasZeissner commented
Our pipelines will fail when the git directory is dirty. This happens on router builds at least automatically.

Didn't saw this as an artifact, clients using it have to ensure those are up to date which is at the moment the terraform-provider which needs to adapt to whatever changes here.

2024-09-13 19:01 UTC, StarpTech commented
Does it mean a workflow will fail when the code becomes outdated in this repo?

2024-09-13 19:26 UTC, AndreasZeissner commented
Not necessarily in the terraform provider. It will fail there when e2e tests are failing which are running against latest cosmo. 

I think it's a good idea to keep the files updated in general.
Nevertheless I think no one will do unless you need to, or the pipeline fails. This would be  latest in the router builds as they are running the generate-go command and do the dirty check, even though it's unrelated.

The controlpalne ci seems to be the only place where this would make sense, even when publishing it somewhere later.

Are there any considerations on reusing things on the router?

2024-09-16 09:27 UTC, StarpTech requested changes

2024-09-16 09:27 UTC, StarpTech commented on buf.connect-go.go.gen.yaml
> +      value: github.com/wundergraph/cosmo/connect-go
Let's stick with the convention of "gen". We do this for router and collector.

2024-09-16 09:41 UTC, StarpTech approved these changes
LGTM

2024-09-16 09:43 UTC, merged