feat: move cache control policy to standalone config section
wundergraph/cosmo pull request #1218
Opened 2024-09-24 18:51 UTC by df-wg

In https://github.com/wundergraph/cosmo/pull/1155, we added in support for having a restrictive cache control policy, as part of the header rules. This pulls out the cache control configuration into a standalone section of the configuration, for clarity and extensibility. 

It can now be configured like: 
```yaml

cache_control_policy:
  enabled: true
  value: "max-age=180, public"
  subgraphs:
    - name: "products"
      value: "max-age=60, public"
```

Additionally, in https://github.com/wundergraph/cosmo/pull/1196 we had created a `set` header operation. This PR adds tests to validate that using the `set` header operation, we can, if necessary, override the cache control restrictions, as a 'break-glass' measure. 

## Motivation and Context

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-09-24 18:54 UTC, df-wg commented on router/core/header_rule_engine.go
> +func (hf *HeaderPropagation) convertCacheToRules(cacheControl config.CacheControlPolicy) {
This is the direction I found simplest - to simply convert the cache control policy object into the appropriate rules. It isn't the only way, and I'm happy to get push-back on it, I had just thought it was the simplest and fastest way of adding in the functionality

2024-09-25 07:30 UTC, StarpTech requested changes

2024-09-25 10:21 UTC, df-wg commented on router/core/header_rule_engine.go
> +	for _, graph := range cacheControl.Subgraphs {
I don't think there's a need fo rthat. It's from their config, and if their config is flawed, do we handle that for them?

2024-09-25 18:56 UTC, StarpTech commented on router/core/header_rule_engine.go
> +	for _, graph := range cacheControl.Subgraphs {
We could add a warning but I'm good to go with it.

2024-09-25 19:00 UTC, StarpTech approved these changes
LGTM

2024-09-26 09:14 UTC, merged