feat: add subgraph access logs
wundergraph/cosmo pull request #1401
Opened 2024-11-26 17:00 UTC by df-wg

## Motivation and Context

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [ ] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [ ] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

2024-11-28 11:29 UTC, StarpTech requested changes

2024-11-28 11:29 UTC, StarpTech commented on router/internal/requestlogger/requestlogger.go
> +func (al accessLogger) getRequestFields(r *http.Request) []zapcore.Field {
Use a pointer receiver.

2024-11-28 11:29 UTC, StarpTech commented on router/internal/requestlogger/subgraphlogger.go
Please ensure that we have covered the most important paths in unit tests.

2024-12-02 16:40 UTC, StarpTech requested changes
Looks very good overall, only nitpicks

2024-12-02 19:05 UTC, df-wg commented on router/pkg/config/config.schema.json
> +                              "operation_name",
From what I could see, the only one that's not available in the subgraph context is `response_error_message` (it is only set by the completion of the full query, and not the subgraph). I removed it, and we'll look into the error logging as part of the next task

2024-12-03 07:15 UTC, StarpTech approved these changes
LGTM

2024-12-03 07:53 UTC, merged