fix(router): use valid format for graphql operation
wundergraph/cosmo pull request #1406
Opened 2024-11-27 19:38 UTC by Noroth

## Motivation and Context

Subgraph names can contain characters which are not valid for using the fetch operation name format. This PR updates the engine version which makes sure to sanitize the operation name during the planning phase.

## Related Engine Release 

https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.129

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [ ] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [ ] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

2024-11-27 19:47 UTC, JivusAyrus approved these changes

2024-11-28 09:07 UTC, StarpTech requested changes
Please add a test

2024-11-29 15:25 UTC, StarpTech approved these changes
LGTM

2024-11-30 13:12 UTC, StarpTech approved these changes
LGTM

2024-12-02 09:26 UTC, merged