feat(router): expose router operation cache metrics
wundergraph/cosmo pull request #1408
Opened 2024-11-29 07:05 UTC by Noroth

## Motivation and Context

Add an option to expose OTEL metrics from `ristretto caches`.

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [ ] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [ ] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

2024-11-29 07:36 UTC, jensneuse approved these changes
Please check with @StarpTech but overall looks good to me except some minor things.

2024-11-29 07:36 UTC, jensneuse commented on router/pkg/metric/cache_metrics.go
> +		otelmetric.WithAttributes(attribute.String("type", "hits")),
Would it make sense to put literals like "type", "hits", "misses", "cache_type", etc. into const strings?

2024-11-29 07:36 UTC, jensneuse commented on router/pkg/metric/cache_metrics.go
> +func (c *CacheMetrics) Observe(
the func name Observe indicates that this func will be blocking. When looking closer, it appears that this is not the case. Maybe different naming could clarify this?

Alternatively, you could add comments to the functions to make the functionality clear.

2024-11-29 10:25 UTC, StarpTech requested changes

2024-11-29 10:25 UTC, StarpTech commented on router/core/graph_server.go
> +	if s.cacheMetrics != nil {
Shutdown when the mux is shutdown

2024-11-29 10:25 UTC, StarpTech commented on router-tests/prometheus_test.go
> +	t.Run("Collect router cache metrics", func(t *testing.T) {
Please separate tests for telemetry and cache details

2024-11-29 10:28 UTC, StarpTech commented on router-tests/prometheus_test.go
> +			for _, c := range cacheMetrics {
Can we simplify this and make assertions more readable?

2024-12-01 11:24 UTC, StarpTech commented on router/pkg/metric/cache_metrics.go
> +			otel.CacheMetricsOperationAttribute.String("evicted"),
We could also move those const to attributes.go. WDYT?

2024-12-02 16:32 UTC, StarpTech approved these changes
LGTM

2024-12-03 08:25 UTC, merged