fix: add regex validation to graph names and routing urls
wundergraph/cosmo pull request #1450
Opened 2024-12-16 20:22 UTC by JivusAyrus

## Checklist

- [x] I have discussed my proposed changes in an issue and have received approval to proceed.
- [x] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [x] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

2024-12-22 12:08 UTC, StarpTech requested changes

2024-12-22 12:08 UTC, StarpTech commented on controlplane/src/core/bufservices/contract/createContract.ts
> +            details: `The name of the contract is invalid. Name should start and end with an alphanumeric character. Only '.', '_', '@', '/', and '-' are allowed as separators in between.`,
Do we also catch min/max length?

2025-01-06 15:27 UTC, JivusAyrus commented on controlplane/src/core/bufservices/contract/createContract.ts
> +            details: `The name of the contract is invalid. Name should start and end with an alphanumeric character. Only '.', '_', '@', '/', and '-' are allowed as separators in between.`,
Done

2025-01-06 15:30 UTC, StarpTech approved these changes
LGTM

2025-01-06 18:02 UTC, merged