feat(router): expose engine statistic metrics
wundergraph/cosmo pull request #1452
Opened 2024-12-17 12:44 UTC by Noroth

## Motivation and Context

We would like to expose metrics for engine statistics related to subscriptions.

* number of active connections
* number of active subscriptions
* number of active triggers
* count of sent messages from the engine

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [ ] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [ ] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

2024-12-20 10:34 UTC, alepane21 reviewed
Just a test for Ludwig

2024-12-20 10:34 UTC, alepane21 submitted a review, later dismissed
Just another test for Ludwig

2024-12-22 15:20 UTC, StarpTech requested changes
Only a few nuts but overall great approach and reuse of WebSocket stats.

2024-12-22 15:20 UTC, StarpTech commented on router/pkg/config/config.schema.json
> +                "engine_stats" : {
We might want to add more in the future. I'd try to be more specific e.g.

```yaml
engine_stats
  connections: true
  websockets: true
```

This also allow the user to opt-in to specific metrics without buying into all metrics which is always a cost factor for them.

2024-12-22 15:27 UTC, StarpTech commented on router/pkg/config/config.schema.json
> +                  "description": "Enable the collection of metrics for the Engine statistics. The default value is false."
Maybe be a bit more verbose in what metrics we will enable and why they are useful.

2024-12-22 15:37 UTC, StarpTech requested changes

2024-12-22 15:37 UTC, StarpTech commented on router/core/graph_server.go
> +			Reporter:                 s.engineStats,
How does it behave with multiple mux? Let's meet about this. In theory each mux has different base attributes and different stats.

2024-12-23 12:07 UTC, StarpTech commented on router/core/graph_server.go
> +			Reporter:                 s.engineStats,
Decided to cover all with the base graph config

2025-01-03 14:31 UTC, StarpTech approved these changes
LGTM

2025-01-06 09:21 UTC, merged