feat: improve rate limiting with better customization
wundergraph/cosmo pull request #1476
Opened 2024-12-23 13:03 UTC by jensneuse

This PR adds the following 2 features:

1. Being able to add a suffix to the rate liming key from a client request header or claim: This allows to rate limit different users. Currently, there's only a global rate limit
2. Being able to return a custom status code when we reject a request, e.g. 429 (can be a company security policy)

2024-12-23 14:36 UTC, StarpTech requested changes

2024-12-23 14:36 UTC, StarpTech commented on router/core/ratelimiter.go
> +			return fmt.Sprintf("%s:%s", ctx.RateLimitOptions.RateLimitKey, v)
We should validate the value. Enforcing a max length and strip leading whitespaces from it.

2024-12-23 14:36 UTC, StarpTech commented on router/core/ratelimiter.go
> +				return fmt.Sprintf("%s:%s", ctx.RateLimitOptions.RateLimitKey, v)
`v` might not be a string. We should validate it.

2024-12-23 14:36 UTC, StarpTech commented on router/pkg/config/config.go
> +	RejectStatusCode        int           `yaml:"reject_status_code" envDefault:"200" env:"RATE_LIMIT_SIMPLE_REJECT_STATUS_CODE"`
Wouldn't this be incompatible with GraphQL over http spec?

2024-12-23 15:14 UTC, StarpTech approved these changes
LGTM

2025-01-02 07:25 UTC, chensunny commented on router/core/ratelimiter.go
> +	if c.keySuffixFromRequestHeader {
police like this 

https://stellate.co/docs/graphql-security/rate-limiting/api-reference

2025-01-07 10:48 UTC, jensneuse commented on router/core/ratelimiter.go
> +	if c.keySuffixFromRequestHeader {
Implemented using expr lang. Thank you for the feedback.

2025-01-07 11:37 UTC, StarpTech commented on router/pkg/config/config.schema.json
> +          "description": "Use Expr-Lang to define a key suffix for the rate limit, e.g. by using request headers, claims, or a combination of both with a fallback strategy."
```suggestion
          "description": "The expression to define a key suffix for the rate limit, e.g. by using request headers, claims, or a combination of both with a fallback strategy. The expression is specified as a string and needs to evaluate to a string. Please see https://expr-lang.org/ for more information."
```

2025-01-07 11:46 UTC, merged