feat: allow to conditionally block mutation via expressions
wundergraph/cosmo pull request #1480
Opened 2024-12-25 12:25 UTC by StarpTech

## Motivation and Context

This pull request introduces the capability to conditionally block mutations, subscriptions, and non-persisted operations. Instead of relying on YAML configuration alone, we have implemented support for dynamic expressions that are evaluated at runtime. Users can leverage request headers, URL parameters, query parameters, and authentication context (such as claims and scopes) to define the condition when operations are blocked. If no condition is provided all operations are blocked.

### Example Configuration

```yaml
security:
  block_mutations:
    enabled: true
    condition: "Request.Header.Get('X-Block-Mutation') == 'yes'"
```

The expression parser and runtime are powered by [expr-lang](https://expr-lang.org/), a widely used library in the Go ecosystem. We chose `expr` for its elegant DSL and robust error reporting.  

During router bootstrap, the system will validate that the expression are valid and returns the expected type (a boolean for conditions). If the expression evaluates to an incorrect type, the process will fail with a detailed error message. 

This step forward, will also lay the foundation for a more dynamic approach in applying configuration or extracting values at runtime.

---  

Let me know if you need further adjustments!

## Checklist

- [ ] I have discussed my proposed changes in an issue and have received approval to proceed.
- [ ] I have followed the coding standards of the project.
- [ ] Tests or benchmarks have been added or updated.
- [ ] Documentation has been updated on [https://github.com/wundergraph/cosmo-docs](https://github.com/wundergraph/cosmo-docs).
- [ ] I have read the [Contributors Guide](https://github.com/wundergraph/cosmo/blob/main/CONTRIBUTING.md).

2025-01-02 11:28 UTC, Noroth commented on router-tests/block_operations_test.go
> +	t.Run("block mutations", func(t *testing.T) {
Test naming could be improved because you are not only testing blocking behavior

```suggestion
	t.Run("test blocking rules for mutations", func(t *testing.T) {
```

2025-01-02 11:29 UTC, Noroth commented on router/core/context.go
> +	"github.com/wundergraph/cosmo/router/internal/expr"
nit: sort imports

2025-01-02 11:33 UTC, Noroth commented on router/core/context.go
> +	// expressionContext is the context for expressions parser when evaluating dynamic expressions
Maybe?
```suggestion
	// expressionContext is the context that will be provided to a compiled expression in order to retrieve data via dynamic expressions
```

2025-01-02 11:35 UTC, Noroth commented on router/core/operation_blocker.go
> +	"go.uber.org/zap"
nit: sort imports

2025-01-02 11:36 UTC, Noroth commented on router/core/websocket.go
> +	"github.com/wundergraph/cosmo/router/internal/expr"
nit: sort imports

2025-01-02 11:37 UTC, Noroth commented on router/internal/expr/expr.go
> +	"reflect"
nit: sort imports

2025-01-02 11:39 UTC, Noroth commented on router/internal/expr/expr.go
> +func (r *RequestRootContext) LoadRequest(req *http.Request) {
This function is basically always called directly after creating a new context with 
`expr.RequestRootContext{}`

Maybe this could be a 
```go
NewFromRequest(req *http.Request) RequestRootContext {}
```

2025-01-02 11:47 UTC, Noroth commented on router/pkg/config/config.go
> +
These types basically are the same and could be simplified into a single type

```suggestion
type BlockConfiguration struct {
	Enabled   bool   `yaml:"enabled" envDefault:"false" env:"ENABLED"`
	Condition string `yaml:"condition" env:"CONDITION"`
}
```

The SecurityConfiguration type could then be replaced with `envPrefix`

Also I think in general the 3 fields cannot have an `env` config anyways as they are complex types?

```go
type SecurityConfiguration struct {
	BlockMutations              BlockMutationConfiguration     `yaml:"block_mutations" envPrefix:"SECURITY_BLOCK_MUTATIONS_"`
	BlockSubscriptions          BlockSubscriptionConfiguration `yaml:"block_subscriptions" envPrefix:"SECURITY_BLOCK_SUBSCRIPTIONS_"`
	BlockNonPersistedOperations BlockNonPersistedConfiguration `yaml:"block_non_persisted_operations" envPrefix:"SECURITY_BLOCK_NON_PERSISTED_OPERATIONS_"`
```

2025-01-02 12:47 UTC, StarpTech commented on router/internal/expr/expr.go
> +	Header RequestHeaders
Yes, could be. Good point.

2025-01-02 15:55 UTC, StarpTech commented on router/internal/expr/expr.go
> +}
There is no need to suffix it with header if the user still reference to `request.header` in the expression

2025-01-02 15:57 UTC, StarpTech commented on router-tests/block_operations_test.go
> +	"github.com/wundergraph/cosmo/router/pkg/config"
Either we automate it or ignore. It is just noise otherwise on a pr review.

2025-01-02 15:58 UTC, StarpTech commented on router-tests/block_operations_test.go
> +	t.Run("block non-persisted operations", func(t *testing.T) {
👍

2025-01-02 16:57 UTC, Noroth commented on router-tests/block_operations_test.go
> +	"github.com/wundergraph/cosmo/router/pkg/config"
gci is a nice formatter for go imports.

2025-01-02 17:13 UTC, StarpTech commented on router/pkg/config/config.go
> +
I like. I use envPrefix.

2025-01-02 17:15 UTC, StarpTech commented on router/internal/expr/expr.go
> +func (r *RequestRootContext) LoadRequest(req *http.Request) {
We would still need to conditionally run `LoadAuth`. I'd then rather keep it consistent with `Load`.

2025-01-02 17:31 UTC, StarpTech commented on router-tests/block_operations_test.go
> +	t.Run("block mutations", func(t *testing.T) {
Improved

2025-01-02 17:32 UTC, StarpTech commented on router/core/context.go
> +	// expressionContext is the context for expressions parser when evaluating dynamic expressions
Updated it in a separate commit, thx

2025-01-03 07:46 UTC, Noroth reviewed
Let me know about my last comment otherwise LGTM

2025-01-03 07:46 UTC, Noroth commented on router/internal/expr/expr.go
>  }
I'm fine with the current solution, this would only be another suggestion to avoid the type casting

```suggestion
type accessor interface{
        Get(string) string
}

type Request struct {
	Auth   RequestAuth    `expr:"auth"`
	URL    RequestURL     `expr:"url"`
	Header accessor `expr:"header"`
}
```

2025-01-03 08:21 UTC, jensneuse requested changes

2025-01-03 08:21 UTC, jensneuse commented on router/core/websocket.go
> +	exprCtx.LoadRequest(registration.clientRequest)
It looks to me like at this point, we've not loaded Auth from the request into the exprCtx.

2025-01-03 08:21 UTC, jensneuse commented on router/internal/expr/expr.go
> +type RequestRootContext struct {
As this is the expression context and we're in the expr package, I'd just call this Context.
As we've discussed in #1481 this context will also contain Response, Field, and other values, so I'd keep it generic.

2025-01-03 08:21 UTC, jensneuse commented on router/internal/expr/expr.go
> +type RequestHeaders map[string][]string
have you considered using http.Header?

2025-01-03 08:21 UTC, jensneuse commented on router/internal/expr/expr.go
> +func (r *RequestRootContext) LoadAuth(ctx context.Context) {
Do you think it's good to split this into a separate public func?
There's a high likelihood that someone forgets to call it.
How about creating a single func to init an expr.Context from a client request?

2025-01-03 08:21 UTC, jensneuse commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
It appears to me as if expr.Run is not thread safe.
I think we need to have a mutex around it, and potentially compile one expr per CPU and then have a slice of expressions (one per CPU) where we can pick one vm from a semaphore.

2025-01-03 08:21 UTC, jensneuse commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
Thread safe?

2025-01-03 09:22 UTC, StarpTech commented on router/internal/expr/expr.go
> +func (r *RequestRootContext) LoadAuth(ctx context.Context) {
That what @Noroth suggested. but`LoadAuth` needs to be called conditionally anyway. For this reason, I wanted to follow the `Load*` pattern rather than going with 2 variants.

2025-01-03 09:27 UTC, StarpTech commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
Why do you think it needs to be thread safe? You suggestions sounds like a big pre optimization that isn't required at this point.

2025-01-03 09:28 UTC, StarpTech commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
Not required by the implementation.

2025-01-03 09:28 UTC, StarpTech commented on router/core/websocket.go
> +	exprCtx.LoadRequest(registration.clientRequest)
Good point, a test is missing.

2025-01-03 09:30 UTC, StarpTech commented on router/internal/expr/expr.go
> +type RequestRootContext struct {
Sounds good to me

2025-01-03 09:43 UTC, StarpTech commented on router/internal/expr/expr.go
>  }
In your proposal, the user won't be able to anymore to access the headers by map. I'm also fine with your direction. We don't have the need yet to do it and an interface is a good way to ensure the right contract.

2025-01-03 09:55 UTC, Noroth approved these changes
LGTM

2025-01-03 09:56 UTC, jensneuse commented on router/internal/expr/expr.go
> +type RequestHeaders map[string][]string
Is this exposed by default or do we have to expose it explicitly?

2025-01-03 09:58 UTC, jensneuse commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
I think it needs to be thread safe because you have one single operation blocker which gets called by many requests in different goroutines.

2025-01-03 09:59 UTC, jensneuse commented on router/internal/expr/expr.go
> +func (r *RequestRootContext) LoadAuth(ctx context.Context) {
Why does it need to be called conditionally? Maybe we can aim to create an env context in a central place for each request?

2025-01-03 10:05 UTC, StarpTech commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
It is thread safe https://github.com/expr-lang/expr/issues/683#issuecomment-2213958821

2025-01-03 10:09 UTC, StarpTech commented on router/internal/expr/expr.go
> +	r, err := expr.Run(vm, ctx)
I revisited the implementation and you're right it is required but luckily `vm.program` is already thread safe.

2025-01-03 11:12 UTC, StarpTech commented on router/internal/expr/expr.go
> +type RequestHeaders map[string][]string
Everything is exposed by default but only exported methods are accessible within the VM.

2025-01-03 11:12 UTC, StarpTech commented on router/internal/expr/expr.go
> +func (r *RequestRootContext) LoadAuth(ctx context.Context) {
Clarified

2025-01-03 11:13 UTC, StarpTech commented on router/core/graphql_prehandler.go
> +		err = h.handleOperation(r, variablesParser, &httpOperation{
I moved auth before we handle the operation. Make sense to me.

2025-01-03 11:14 UTC, StarpTech commented on router/pkg/authentication/authentication.go
> +		// If authentication succeeds, we return the authentication
This was a flaw. As long as the authenticator return no error, we can assume the authentication was successful even when no claims have been configured.

2025-01-03 12:37 UTC, jensneuse approved these changes

2025-01-03 12:41 UTC, merged