test: use random ports in integration tests
wundergraph/cosmo pull request #188
Opened 2023-10-13 12:18 UTC by fiam

Use wgc to generate the configuration with the random ports on demand

## Motivation and Context

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2023-10-13 12:59 UTC, jensneuse approved these changes

2023-10-13 13:17 UTC, StarpTech requested changes

2023-10-13 13:17 UTC, StarpTech commented on router-tests/go.mod
> +toolchain go1.21.2
This produces a build error. What does bring us?

2023-10-13 13:18 UTC, StarpTech requested changes

2023-10-13 13:18 UTC, StarpTech commented on router-tests/runner/runner.go
> +	for ii := range ports {
Just `i`?

2023-10-13 14:51 UTC, StarpTech approved these changes
LGTM

2023-10-14 16:48 UTC, fiam commented
This one needs #187 and a release because we're using absolute paths for the wgc output file

2023-10-16 13:39 UTC, merged