fix: remove unnecessary fields and add populate the createdBy for compositions
wundergraph/cosmo pull request #272
Opened 2023-11-17 21:15 UTC by JivusAyrus

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2023-11-17 22:52 UTC, StarpTech approved these changes
LGTM

2023-11-18 11:06 UTC, StarpTech requested changes

2023-11-18 11:06 UTC, StarpTech commented on controlplane/src/bin/version-migration.ts
Don't forget to delete script in package.json

2023-11-20 09:03 UTC, JivusAyrus commented on controlplane/src/bin/version-migration.ts
Done

2023-11-20 09:39 UTC, StarpTech approved these changes
LGTM

2023-11-20 09:53 UTC, merged