feat: implement slider for analytics duration
wundergraph/cosmo pull request #539
Opened 2024-02-15 22:01 UTC by JivusAyrus

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-02-16 10:02 UTC, StarpTech requested changes

2024-02-16 10:02 UTC, StarpTech commented on controlplane/src/core/repositories/analytics/SubgraphMetricsRepository.ts
> +      customOptions: CustomOptions.Text,
Please also use the slider in P95 latency of the analytics views.

2024-02-17 20:02 UTC, JivusAyrus commented on studio/src/components/analytics/data-table-faceted-filter.tsx
> +      content = (
Done

2024-02-17 20:03 UTC, JivusAyrus commented on proto/wg/cosmo/platform/v1/platform.proto
> +}
To the backend i send the min and max values separately with their respective operators, so the interface we use still works

2024-02-20 08:54 UTC, StarpTech approved these changes
LGTM

2024-02-20 11:09 UTC, merged