fix: handle empty files in the cli itself
wundergraph/cosmo pull request #593
Opened 2024-03-01 18:23 UTC by JivusAyrus

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-03-04 08:00 UTC, jensneuse requested changes

2024-03-04 08:00 UTC, jensneuse commented on cli/src/commands/subgraph/commands/fix.ts
> +    if (schema.length === 0) {
What if a schema contains some whitespace, like a newline, space or tab?

2024-03-04 08:50 UTC, StarpTech commented on cli/src/commands/subgraph/commands/fix.ts
> +    if (schema.length === 0) {
Do a `trim()` before :smile:

2024-03-08 09:37 UTC, StarpTech approved these changes
LGTM

2024-03-08 15:26 UTC, jensneuse approved these changes

2024-03-08 15:45 UTC, merged