Suvij/eng 5042 let everybody create orgs
wundergraph/cosmo pull request #709
Opened 2024-04-08 20:12 UTC by JivusAyrus

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-04-08 21:43 UTC, StarpTech requested changes

2024-04-08 21:43 UTC, StarpTech commented on studio/src/pages/create.tsx
> +          disabled={!form.formState.isValid}
Do we enforce max organizations?

2024-04-09 14:00 UTC, JivusAyrus commented on studio/src/pages/create.tsx
> +          disabled={!form.formState.isValid}
No, as every new org is a paid org

2024-04-09 15:41 UTC, StarpTech approved these changes
LGTM

2024-04-11 14:50 UTC, merged