feat: Add istioGateway and VirtualService to router helm chart
wundergraph/cosmo pull request #773
Opened 2024-05-08 16:10 UTC by jeffutter

## Motivation and Context

We use Istio and `istioGateway`/`VirtualService` rather than an ingress. We also don't have any plans to support the newer `ingressGateway`. This should provide the necessary resources to create the `istioGateway` and `VirtualService` (disabled by default).

## TODO

- [x] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-05-08 16:26 UTC, tristan-secord approved these changes

2024-05-10 18:26 UTC, StarpTech requested changes

2024-05-10 18:26 UTC, StarpTech commented on helm/cosmo/charts/router/templates/gateway.yaml
> +{{- if .Values.istioGateway -}}
Does the config requires a specific Istio version? If yes, please make a comment in the config.

2024-05-10 18:26 UTC, StarpTech commented on helm/cosmo/charts/router/templates/gateway.yaml
> +  {{- range .Values.istioGateway.hosts }}
Please provide default values for all possible options in the values.yaml. If we add a`# -- ` comment to all values we can auto generate the docs. Don't forget to run `make docs` in the `helm` directory.

2024-05-10 18:26 UTC, StarpTech commented on helm/cosmo/charts/router/templates/gateway.yaml
> +apiVersion: networking.istio.io/v1beta1
I'd recommend to split this into `virtual-service.yml` and `gateway.yml`

2024-05-10 19:56 UTC, jeffutter commented
@StarpTech Rebased and addressed all of the issues ( I think ). Let me know if I'm missing anything.

2024-05-11 19:24 UTC, StarpTech commented
@jeffutter awesome, looks good.

2024-05-11 19:25 UTC, StarpTech commented on helm/cosmo/charts/router/values.yaml
> +  # enabled: true
@jeffutter Last point. Comment it out so it is listed in the options too.

2024-05-13 13:25 UTC, StarpTech approved these changes
LGTM

2024-05-13 13:25 UTC, merged