David/eng 5153 implement subscription filter
wundergraph/cosmo pull request #780
Opened 2024-05-10 15:07 UTC by Aenimus

## Motivation and Context

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-05-16 18:00 UTC, StarpTech requested changes
Only one point other than that great work!

2024-05-16 18:40 UTC, Aenimus commented on router/config.yaml
> +version: "1"
It's just removed the newline.

2024-05-17 07:10 UTC, jensneuse approved these changes
I think you've implemented unnecessarily overlapping tests.
The filter is transport agnostic as it's implemented in the engine.
If we change something in the future, we'd have to change all tests for all transports, but we're not getting any additional value from these overlapping tests.
If I'm not missing something, I'd prefer to have as few tests as possible and as many as they are adding additional test coverage, which is not the case here.

That said, looks very good!

2024-05-21 18:10 UTC, StarpTech approved these changes
LGTM

2024-05-21 18:21 UTC, merged