feat: use Helm tpl function on .Values.commonConfiguration
wundergraph/cosmo pull request #840
Opened 2024-05-30 16:52 UTC by bbil

## Motivation and Context

Allows users of the Helm chart to use dynamic content for `.Values.commonConfiguration` string -- used in the Config Map.

```
commonConfiguration: |-
  headers:
    subgraphs:
      someSubgraph:
        {{- include "subgraph.headers" . | nindent 6 }}
```

Without this change, `.Values.commonConfiguration` is just a string, and the dynamic part does not get expanded.        

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-05-30 16:56 UTC, bbil commented
This will also require a bump on the Chart version, should I also be doing this bump in this PR?

Also, I'm wondering if there's a good way to test this out locally... I've tested this works with a dummy config map yaml file, so I think it should be fine. But messing with Helm is always kinda sketchy to me, with understanding if this is going to be fine in a full end-to-end setup.

2024-05-31 17:39 UTC, jeffutter commented
👍 I like this idea. As far as I understand, shouldn't change anything for existing users that don't have things that look like templates in their configs.

2024-06-03 08:57 UTC, StarpTech commented
Hi @bbil, thank you for the PR. We have established a local setup with minikube to test our Helm charts. I can guide you through at some point when you're doing more significant work in the Helm charts.

> This will also require a bump on the Chart version, should I also be doing this bump in this PR?

Yes, please bump minor. The release is still manual after merge to main.

2024-06-03 08:58 UTC, StarpTech requested changes

2024-06-03 08:58 UTC, StarpTech commented on helm/cosmo/charts/router/templates/config-map.yaml
> +    {{- tpl .Values.commonConfiguration . | nindent 4 }}
Could you document this behaviour in the chart comments of `commonConfiguration ` ? After running `make docs`, the docs are regenerated.

2024-06-03 16:20 UTC, jeffutter commented
@StarpTech Brandon is out this week, so I'll be helping out here. I bumped the minor version and updated the docs. In updating the docs I noticed that there were a few other comments which had multiple lines that were only including the last line. I fixed those as well.

Please let me know if there are any other changes you would like to see.

2024-06-03 17:11 UTC, StarpTech commented
@jeffutter thank you 👏

2024-06-03 17:33 UTC, StarpTech approved these changes
LGTM

2024-06-03 20:25 UTC, merged

2024-06-03 20:26 UTC, StarpTech commented
Published as 0.4.0