feat: handle creating, publishing, and updating Event-Driven Graphs
wundergraph/cosmo pull request #855
Opened 2024-06-05 08:54 UTC by Aenimus

## Motivation and Context

## TODO

- [ ] Tests or benchmark included
- [ ] Documentation is changed or added on [https://app.gitbook.com/](https://app.gitbook.com/)
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)

2024-06-05 16:43 UTC, StarpTech approved these changes
LGTM

2024-06-06 08:40 UTC, thisisnithin requested changes

2024-06-06 08:40 UTC, thisisnithin commented on controlplane/migrations/0089_wandering_domino.sql
> +ALTER TABLE "subgraphs" ADD COLUMN "is_event_driven_graph" boolean DEFAULT false NOT NULL;
This `0089_` migration is a duplicate. Please delete

2024-06-06 11:17 UTC, thisisnithin approved these changes

2024-06-06 11:50 UTC, merged